#!/usr/bin/python

import urllib2
import os
import sys

def get_metrics(host, port):
    ret = urllib2.urlopen( "http://" + host + ":" + str(port) + "/api/plugins" ).read()
    return parse(ret)

def parse(vals):
    params = [];
    for val in vals.splitlines():
        param = {}
        for p in val.split():
            if "plugin_id:" in p:
                k,v,i = p.split(':')
                param[k] = i
            else:
                k,v = p.split(':')
                param[k] = v
        params.append(param)
    return params

def munin(host, port):
    params = get_metrics(host, port)
    plugin_counter = {}
    for param in params:
        if param.pop('output_plugin') != 'true':
            continue
        id = param.pop('plugin_id')
        type = None
        if "type" in param.keys():
            type = param.pop('type')
        if type == None:
            continue
        num_id = 1
        if type in plugin_counter.keys():
            num_id = plugin_counter[type] + 1
            plugin_counter[type] = num_id
        else:
            plugin_counter[type] = num_id

        for k in param:
            print type + "_" + str(num_id) + "_" + k + ".value " + param[k]

def config():
    print "graph_title fluentd monitor_agent usage"
    print "graph_category fluentd"


if __name__ == "__main__":
    if os.environ.get('host'):
        host = os.environ.get('host')
    else: 
        host = 'localhost'

    if os.environ.get('port'):
        port = os.environ.get('port')
    else: 
        port = 24220

    if len(sys.argv) > 1 and sys.argv[1] == "config":
        config()
    else:
        munin(host, port)


